name: MicroHs CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: make
      run: make
    - name: make everytestmhs
      run: make everytestmhs
    - name: cabal build
      run: cabal build

  build-linux-micro-x86_64:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: make
      run: make CONF=micro-64

  build-macos:
    runs-on: macos-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: make
      run: make
    - name: make everytestmhs
      run: make everytestmhs
    - name: cabal build
      run: cabal build

  build-windows:
    runs-on: windows-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: nmake
      run: nmake -f Makefile.windows
  #  - name: nmake exampletest
  #    run: nmake -f Makefile.windows exampletest

  build-linux-aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: jirutka/setup-alpine@v1
      with:
        arch: aarch64
        branch: v3.15
        packages: >
          build-base
          gcc
          make
    - name: checkout repo
      uses: actions/checkout@v3
    - name: make
      run: make
    - name: make everytestmhs
      run: make everytestmhs
#    - name: cabal build
#      run: cabal build

  build-linux-s390x:
    runs-on: ubuntu-latest
    steps:
    - uses: jirutka/setup-alpine@v1
      with:
        arch: s390x
        branch: v3.15
        packages: >
          build-base
          gcc
          make
    - name: checkout repo
      uses: actions/checkout@v3
    - name: make
      run: make
    - name: make everytestmhs
      run: make everytestmhs
#    - name: cabal build
#      run: cabal build

# Not supported by alpine
#  build-linux-riscv64:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: jirutka/setup-alpine@v1
#      with:
#        arch: riscv64
#        branch: v3.15
#        packages: >
#          build-base
#          gcc
#          make
#    - name: checkout repo
#      uses: actions/checkout@v3
#    - name: make
#      run: make
#    - name: make everytestmhs
#      run: make everytestmhs
#    - name: cabal build
#      run: cabal build

  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
    - uses: jirutka/setup-alpine@v1
      with:
        arch: x86
        branch: v3.15
        packages: >
          build-base
          gcc
          make
    - name: checkout repo
      uses: actions/checkout@v3
    - name: make
      run: make CONF=unix-32
      shell: alpine.sh {0}
    - name: make everytestmhs
      run: make CONF=unix-32 everytestmhs
      shell: alpine.sh {0}

  build-linux-armv7:
    runs-on: ubuntu-latest
    steps:
    - uses: jirutka/setup-alpine@v1
      with:
        arch: armv7
        branch: v3.15
        packages: >
          build-base
          gcc
          make
    - name: checkout repo
      uses: actions/checkout@v3
    - name: make
      run: make CONF=unix-32
      shell: alpine.sh {0}
    - name: make everytestmhs
      run: make CONF=unix-32 everytestmhs
      shell: alpine.sh {0}

  build-linux-emscripten:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: mymindstorm/setup-emsdk@v13
     - uses: actions/setup-node@v4
     - name: run emscripten tests
       run: make emscripten

# macos-emscripten crashes randomly, so comment it out for now
#  build-macos-emscripten:
#    runs-on: macos-latest
#    steps:
#     - uses: actions/checkout@v3
#     - uses: mymindstorm/setup-emsdk@v13
#     - uses: actions/setup-node@v4
#     - name: run emscripten tests
#       run: make emscripten
